"""Phase 2 Stage B — dedup tests.

Pins:
  - Two languages with identical specs and different slot_ids get grouped.
  - Two languages with mostly-identical specs but one different
    customization field do NOT get grouped.
  - The representative is the one with the highest quality score.
  - Three-way duplicates collapse to one representative + two duplicates.
  - Empty input returns empty output.
  - Same input twice → same output (idempotent).
"""
from __future__ import annotations

import json
import copy
from pathlib import Path

import pytest

from forge.catalog.dedup import (
    dedup_languages,
    dedup_summary,
    fingerprint,
    result_to_dict,
    _overall_score,
)
from forge.catalog.quality import (
    CompletenessResult,
    CorrectnessResult,
    CoherenceResult,
    DistinctivenessResult,
    QualityReport,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write_spec(lang_dir: Path, spec: dict) -> None:
    lang_dir.mkdir(parents=True, exist_ok=True)
    (lang_dir / "resolved_spec.json").write_text(
        json.dumps(spec, indent=2), encoding="utf-8"
    )


def _make_report(*, slot_id: str, lang_dir: Path,
                 correctness_passed: bool = True,
                 distinctiveness: float = 0.5,
                 coherence: float = 1.0,
                 completeness: float = 1.0,
                 family: str = "c_like") -> QualityReport:
    """Build a synthetic QualityReport for testing."""
    return QualityReport(
        slot_id=slot_id,
        lang_dir=str(lang_dir.resolve()),
        family=family,
        pipeline_path="templated",
        correctness=CorrectnessResult(
            passed=correctness_passed,
            canonical_tests={"passed": 8 if correctness_passed else 0,
                             "total": 8, "pass_rate": 1.0,
                             "source": "fixture"},
            kata_pack=None,
            repl={"repl_html_ok": True, "compile_exit_code": 0,
                  "launches": True},
            failures=[] if correctness_passed else ["canonical: 0/8"],
            skips=[],
        ),
        distinctiveness=DistinctivenessResult(
            score=distinctiveness, surface=distinctiveness,
            persona=distinctiveness, variety=distinctiveness, notes=[],
        ),
        coherence=CoherenceResult(
            score=coherence,
            overrides_unique=True, readme_mentions_name=True,
            readme_length_ok=True, stdlib_naming_consistent=True,
            notes=[],
        ),
        completeness=CompletenessResult(
            score=completeness, present=[], missing=[]
        ),
        overall_passed=correctness_passed and completeness >= 0.8,
        rejection_reason=None if correctness_passed else "test fixture failure",
        scored_at="2026-05-08T00:00:00Z",
    )


_BASE_SPEC = {
    "lang_name": "alpha",
    "display_name": "alpha",
    "options": {"syntax": "c_like", "typing": "dynamic", "memory": "host_gc"},
    "customization": {"persona": None, "era": None, "theme": None,
                      "phrasebook": None, "feature_bans": []},
    "comment_syntax": {"line": "//", "block_open": "/*", "block_close": "*/"},
    "file_extension": ".al",
    "statement_terminator": ";",
    "creative": {"readme_intro": "alpha is a baseline c_like language."},
    "origin_story": "alpha was generated by the test suite.",
}


# ---------------------------------------------------------------------------
# Fingerprint properties
# ---------------------------------------------------------------------------

def test_fingerprint_equal_for_specs_differing_only_in_lang_name(tmp_path):
    """Two slots whose resolved specs differ only in lang_name and
    display_name MUST hash identically — that's the entire point of
    dedup. (The resolver cache key uses the same approach.)"""
    a_dir = tmp_path / "a"
    b_dir = tmp_path / "b"
    spec_a = copy.deepcopy(_BASE_SPEC)
    spec_a["lang_name"] = "alpha"
    spec_a["display_name"] = "alpha"
    spec_b = copy.deepcopy(_BASE_SPEC)
    spec_b["lang_name"] = "beta"
    spec_b["display_name"] = "beta"
    _write_spec(a_dir, spec_a)
    _write_spec(b_dir, spec_b)
    r_a = _make_report(slot_id="a", lang_dir=a_dir)
    r_b = _make_report(slot_id="b", lang_dir=b_dir)
    assert fingerprint(r_a) == fingerprint(r_b)


def test_fingerprint_differs_on_keyword_overrides(tmp_path):
    a_dir = tmp_path / "a"
    b_dir = tmp_path / "b"
    spec_a = copy.deepcopy(_BASE_SPEC)
    spec_b = copy.deepcopy(_BASE_SPEC)
    spec_b["customization"]["keyword_overrides"] = {"var": "loot"}
    _write_spec(a_dir, spec_a)
    _write_spec(b_dir, spec_b)
    r_a = _make_report(slot_id="a", lang_dir=a_dir)
    r_b = _make_report(slot_id="b", lang_dir=b_dir)
    assert fingerprint(r_a) != fingerprint(r_b)


def test_fingerprint_differs_on_options(tmp_path):
    a_dir = tmp_path / "a"
    b_dir = tmp_path / "b"
    spec_a = copy.deepcopy(_BASE_SPEC)
    spec_b = copy.deepcopy(_BASE_SPEC)
    spec_b["options"] = dict(spec_b["options"])
    spec_b["options"]["memory"] = "refcount"
    _write_spec(a_dir, spec_a)
    _write_spec(b_dir, spec_b)
    r_a = _make_report(slot_id="a", lang_dir=a_dir)
    r_b = _make_report(slot_id="b", lang_dir=b_dir)
    assert fingerprint(r_a) != fingerprint(r_b)


def test_fingerprint_ignores_creative_output(tmp_path):
    """Two languages with identical specs but different generated
    origin_stories are NOT duplicates per the documented design choice
    (creative content can be substantively different even when the
    structural spec is identical)."""
    a_dir = tmp_path / "a"
    b_dir = tmp_path / "b"
    spec_a = copy.deepcopy(_BASE_SPEC)
    spec_b = copy.deepcopy(_BASE_SPEC)
    spec_a["origin_story"] = "Story A — short."
    spec_b["origin_story"] = "Story B — completely different content here."
    spec_a["creative"] = {"readme_intro": "Intro A"}
    spec_b["creative"] = {"readme_intro": "Intro B (different)"}
    # Both ALSO need different lang_names so they're distinct test
    # entries (otherwise fingerprint test 1 already passes here).
    spec_a["lang_name"] = "alpha"
    spec_b["lang_name"] = "beta"
    _write_spec(a_dir, spec_a)
    _write_spec(b_dir, spec_b)
    r_a = _make_report(slot_id="a", lang_dir=a_dir)
    r_b = _make_report(slot_id="b", lang_dir=b_dir)
    # Per the design: creative output is excluded from the fingerprint,
    # so these still hash identically.
    assert fingerprint(r_a) == fingerprint(r_b)


def test_fingerprint_handles_missing_spec(tmp_path):
    """If resolved_spec.json is missing, fingerprint should still
    produce a deterministic value (based on slot_id) so dedup doesn't
    crash on a partially-broken language directory."""
    lang_dir = tmp_path / "no_spec"
    lang_dir.mkdir()
    r = _make_report(slot_id="no_spec", lang_dir=lang_dir)
    fp1 = fingerprint(r)
    fp2 = fingerprint(r)
    assert fp1 == fp2  # deterministic
    assert fp1  # non-empty


# ---------------------------------------------------------------------------
# Dedup grouping
# ---------------------------------------------------------------------------

def test_dedup_groups_two_clones(tmp_path):
    a_dir = tmp_path / "a"
    b_dir = tmp_path / "b"
    spec_a = copy.deepcopy(_BASE_SPEC); spec_a["lang_name"] = "a"
    spec_b = copy.deepcopy(_BASE_SPEC); spec_b["lang_name"] = "b"
    _write_spec(a_dir, spec_a); _write_spec(b_dir, spec_b)
    reports = [
        _make_report(slot_id="slot_a", lang_dir=a_dir),
        _make_report(slot_id="slot_b", lang_dir=b_dir),
    ]
    results = dedup_languages(reports)
    assert len(results) == 1
    assert len(results[0].duplicate_slot_ids) == 1


def test_dedup_keeps_distinct_languages_separate(tmp_path):
    a_dir = tmp_path / "a"
    b_dir = tmp_path / "b"
    spec_a = copy.deepcopy(_BASE_SPEC)
    spec_b = copy.deepcopy(_BASE_SPEC)
    spec_b["customization"] = dict(spec_b["customization"])
    spec_b["customization"]["theme"] = "pirate"
    _write_spec(a_dir, spec_a); _write_spec(b_dir, spec_b)
    reports = [
        _make_report(slot_id="slot_a", lang_dir=a_dir),
        _make_report(slot_id="slot_b", lang_dir=b_dir),
    ]
    results = dedup_languages(reports)
    assert len(results) == 2
    assert all(not r.duplicate_slot_ids for r in results)


def test_dedup_picks_highest_scoring_as_representative(tmp_path):
    """Two duplicates: the one with higher overall_score wins."""
    a_dir = tmp_path / "low_quality"
    b_dir = tmp_path / "high_quality"
    spec_a = copy.deepcopy(_BASE_SPEC); spec_a["lang_name"] = "a"
    spec_b = copy.deepcopy(_BASE_SPEC); spec_b["lang_name"] = "b"
    _write_spec(a_dir, spec_a); _write_spec(b_dir, spec_b)
    reports = [
        _make_report(slot_id="slot_low", lang_dir=a_dir,
                     distinctiveness=0.1, coherence=0.5,
                     completeness=0.85),
        _make_report(slot_id="slot_high", lang_dir=b_dir,
                     distinctiveness=0.9, coherence=1.0,
                     completeness=1.0),
    ]
    results = dedup_languages(reports)
    assert len(results) == 1
    assert results[0].representative_slot_id == "slot_high"
    assert "slot_low" in results[0].duplicate_slot_ids


def test_dedup_three_way_collapse(tmp_path):
    """Three duplicates collapse to one + two."""
    a_dir = tmp_path / "a"; b_dir = tmp_path / "b"; c_dir = tmp_path / "c"
    spec = copy.deepcopy(_BASE_SPEC)
    for d, name in [(a_dir, "a"), (b_dir, "b"), (c_dir, "c")]:
        s = copy.deepcopy(spec); s["lang_name"] = name
        _write_spec(d, s)
    reports = [
        _make_report(slot_id="slot_a", lang_dir=a_dir, distinctiveness=0.5),
        _make_report(slot_id="slot_b", lang_dir=b_dir, distinctiveness=0.9),
        _make_report(slot_id="slot_c", lang_dir=c_dir, distinctiveness=0.3),
    ]
    results = dedup_languages(reports)
    assert len(results) == 1
    assert results[0].representative_slot_id == "slot_b"
    assert sorted(results[0].duplicate_slot_ids) == ["slot_a", "slot_c"]


def test_dedup_correctness_passing_beats_failing(tmp_path):
    """A passing-correctness duplicate beats a failing-correctness one
    even when the failing one would otherwise score higher on graded
    dimensions."""
    a_dir = tmp_path / "a"; b_dir = tmp_path / "b"
    spec = copy.deepcopy(_BASE_SPEC)
    _write_spec(a_dir, copy.deepcopy(spec))
    _write_spec(b_dir, copy.deepcopy(spec))
    reports = [
        _make_report(slot_id="slot_broken_high",
                     lang_dir=a_dir,
                     correctness_passed=False,
                     distinctiveness=0.9, coherence=1.0,
                     completeness=1.0),
        _make_report(slot_id="slot_working_low",
                     lang_dir=b_dir,
                     correctness_passed=True,
                     distinctiveness=0.1, coherence=0.5,
                     completeness=0.9),
    ]
    results = dedup_languages(reports)
    assert len(results) == 1
    assert results[0].representative_slot_id == "slot_working_low"


def test_dedup_tie_break_by_slot_id(tmp_path):
    """Equal scores → lower slot_id alphabetically wins. Pins
    deterministic output ordering."""
    a_dir = tmp_path / "a"; b_dir = tmp_path / "b"
    spec = copy.deepcopy(_BASE_SPEC)
    _write_spec(a_dir, copy.deepcopy(spec))
    _write_spec(b_dir, copy.deepcopy(spec))
    reports = [
        _make_report(slot_id="zzz", lang_dir=a_dir,
                     distinctiveness=0.5, coherence=0.5, completeness=1.0),
        _make_report(slot_id="aaa", lang_dir=b_dir,
                     distinctiveness=0.5, coherence=0.5, completeness=1.0),
    ]
    results = dedup_languages(reports)
    assert results[0].representative_slot_id == "aaa"


def test_dedup_empty_input():
    assert dedup_languages([]) == []


def test_dedup_idempotent(tmp_path):
    """Same input twice → same output."""
    a_dir = tmp_path / "a"; b_dir = tmp_path / "b"; c_dir = tmp_path / "c"
    spec_ab = copy.deepcopy(_BASE_SPEC)
    spec_c = copy.deepcopy(_BASE_SPEC)
    spec_c["customization"] = dict(spec_c["customization"])
    spec_c["customization"]["theme"] = "pirate"
    _write_spec(a_dir, spec_ab); _write_spec(b_dir, spec_ab)
    _write_spec(c_dir, spec_c)
    reports = [
        _make_report(slot_id="a", lang_dir=a_dir),
        _make_report(slot_id="b", lang_dir=b_dir),
        _make_report(slot_id="c", lang_dir=c_dir),
    ]
    r1 = dedup_languages(reports)
    r2 = dedup_languages(reports)
    assert [result_to_dict(x) for x in r1] == [result_to_dict(x) for x in r2]


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def test_dedup_summary_aggregates_correctly(tmp_path):
    a_dir = tmp_path / "a"; b_dir = tmp_path / "b"
    c_dir = tmp_path / "c"; d_dir = tmp_path / "d"
    spec_ab = copy.deepcopy(_BASE_SPEC)
    spec_cd = copy.deepcopy(_BASE_SPEC)
    spec_cd["customization"] = dict(spec_cd["customization"])
    spec_cd["customization"]["theme"] = "pirate"
    _write_spec(a_dir, spec_ab); _write_spec(b_dir, spec_ab)
    _write_spec(c_dir, spec_cd); _write_spec(d_dir, spec_cd)
    reports = [
        _make_report(slot_id="a", lang_dir=a_dir),
        _make_report(slot_id="b", lang_dir=b_dir),
        _make_report(slot_id="c", lang_dir=c_dir),
        _make_report(slot_id="d", lang_dir=d_dir),
    ]
    results = dedup_languages(reports)
    assert len(results) == 2  # two distinct fingerprints, each with 2 members
    summary = dedup_summary(results)
    assert summary["total_reports"] == 4
    assert summary["unique_languages"] == 2
    assert summary["duplicates_collapsed"] == 2
    assert summary["largest_group_size"] == 2


def test_dedup_summary_empty():
    summary = dedup_summary([])
    assert summary == {
        "total_reports": 0, "unique_languages": 0,
        "duplicates_collapsed": 0, "largest_group_size": 0,
    }


# ---------------------------------------------------------------------------
# Score weighting
# ---------------------------------------------------------------------------

def test_overall_score_weights_match_spec(tmp_path):
    """The weights are 2.0 (correctness) + 1.5 (completeness) +
    1.0 + 1.0 = 5.5 max. A perfect language hits exactly that."""
    spec_dir = tmp_path / "lang"
    _write_spec(spec_dir, copy.deepcopy(_BASE_SPEC))
    perfect = _make_report(
        slot_id="perfect", lang_dir=spec_dir,
        correctness_passed=True,
        distinctiveness=1.0, coherence=1.0, completeness=1.0,
    )
    assert _overall_score(perfect) == 2.0 + 1.5 + 1.0 + 1.0
    # Failing-correctness with everything else max → 0 + 1.5 + 1 + 1 = 3.5
    failing = _make_report(
        slot_id="failing", lang_dir=spec_dir,
        correctness_passed=False,
        distinctiveness=1.0, coherence=1.0, completeness=1.0,
    )
    assert _overall_score(failing) == 0.0 + 1.5 + 1.0 + 1.0
