"""slot_lgc_007, generated by Language Forge.

Options: syntax=logic_like, typing=dynamic, memory=host_gc.
File extension: .slo

This package is self-contained: install with `pip install -e .` from this
directory and the `slot_lgc_007` console command becomes available.
"""
__version__ = "0.1.0"
